[package]
name = "weather_2"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive", "env"] }
reqwest = { workspace = true }
serde_json = "1.0.133"
url = "2.5.4"
